name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for giant-dns demo
      run: docker build . --file Dockerfile --tag giant-dns:$(date +%s)
